# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "zap-0.9.1-GoeB85JTJAADY1vAnA4lTuU66t6JJiuhGos5ex6CpifA";
    path = fetchgit {
      url = "https://github.com/zigzap/zap?ref=v0.10.1";
      rev = "ec7cac6f6ab8e1892fe6fc499fd37cd93f7b2256";
      hash = "sha256-OubbUvSfV0LscV07Ppmjo/hxWyGMILk6c28l8hRmPHA=";
    };
  }
  {
    name = "zdt-0.6.6-xr0_vK3uEQBT67DAH4srPjIYZSA3MJUAGglcm_NBSpUi";
    path = fetchgit {
      url = "https://codeberg.org/FObersteiner/zdt.git";
      rev = "1ee0e311703d06748a4da92717b4cde0edd308a9";
      hash = "sha256-KYbt+g8DvJKEvwE8WXMbfD1nIC7kJPKP5RKTyjXOQ90=";
    };
  }
]
